#!/usr/bin/env python3
"""scripts/architect.py — Architect v2 autonomous agent hooks.

Scope (Issue #4 / Step 6 + Step 11 audit + feedback loop):
- HERMES_AGENT_ENABLED kill switch (env gate, default OFF)
- dry-run (no side-effects)
- File generation (not string patch) — all changes via generate_file()
- EXPLAIN pre-flight before executing migrations / SQL
- gh PR creation via subprocess
- Webhook notification (HERMES_WEBHOOK_URL)
- hits.jsonl logger + pin-memory weighted boost (pin_weight, ttl)
- Audit compatibility with sql/migrations V3 (agent_decision_audit, schema_change_audit)

Pin-memory weighted boost (Librarian C10 tuning):
    boosted = base_score * (1 + pin_weight * ttl_decay)
    ttl_decay = exp(-age_seconds / ttl_seconds)  if ttl > 0 else 1.0
    age = now - pinned_at
"""
from __future__ import annotations

import argparse
import datetime
import hashlib
import json
import math
import os
import re
import subprocess
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

# ---------------------------------------------------------------------------
# Kill switch
# ---------------------------------------------------------------------------

def is_agent_enabled(env: dict | None = None) -> bool:
    """Return True iff HERMES_AGENT_ENABLED is truthy.

    Accepts "1", "true", "yes", "on" (case-insensitive).  Default OFF when
    unset or any other value, including "0"/"false"/"no"/"".
    """
    src = env if env is not None else os.environ
    raw = str(src.get("HERMES_AGENT_ENABLED", "")).strip().lower()
    return raw in ("1", "true", "yes", "on", "enabled")


def require_enabled(force: bool = False) -> bool:
    """Gate helper — returns True if agent may proceed; False if blocked.

    If --force is passed the gate is bypassed (useful for local testing).
    Callers should exit early with code 0 when blocked so CI treats the
    skip as success rather than failure.
    """
    if force:
        return True
    return is_agent_enabled()


# ---------------------------------------------------------------------------
# File generation (not string patch)
# ---------------------------------------------------------------------------

def generate_file(path: Path, content: str, dry_run: bool = False) -> dict:
    """Generate a file atomically; no in-place string patches.

    Returns dict with {path, written, dry_run, checksum, size}.
    In dry-run mode nothing is written and `written` is False.
    """
    p = Path(path)
    checksum = hashlib.sha256(content.encode("utf-8")).hexdigest()
    info = {
        "path": str(p),
        "written": False,
        "dry_run": dry_run,
        "checksum": checksum,
        "size": len(content.encode("utf-8")),
    }
    if dry_run:
        return info
    p.parent.mkdir(parents=True, exist_ok=True)
    # atomic write via temp + rename
    tmp = p.with_suffix(p.suffix + ".tmp")
    tmp.write_text(content, encoding="utf-8")
    tmp.replace(p)
    info["written"] = True
    return info


def generate_migration_file(
    migrations_dir: Path,
    version: str,
    description: str,
    sql_body: str,
    dry_run: bool = False,
) -> dict:
    """Generate a new sql/migrations/V{n}__{description}.sql file.

    version: e.g. "V4" or "V4__add_feature" (normalized to V4__snake_case).
    No string patching — the file is rendered from a template.
    """
    migrations_dir = Path(migrations_dir)
    # normalize version
    m = re.match(r"^(V\d+)(?:__(.*))?$", version)
    if not m:
        raise ValueError(f"invalid migration version: {version!r} (expected V{{n}} or V{{n}}__desc)")
    ver = m.group(1)
    desc = m.group(2) or re.sub(r"[^a-z0-9]+", "_", description.lower()).strip("_")
    desc = re.sub(r"[^a-z0-9_]+", "_", desc.lower()).strip("_") or "migration"
    filename = f"{ver}__{desc}.sql"
    header = (
        f"-- {filename} — auto-generated by scripts/architect.py\n"
        f"-- Idempotent via IF NOT EXISTS where applicable.\n\n"
        f"SET search_path = public;\n\n"
    )
    content = header + sql_body.strip() + "\n"
    return generate_file(migrations_dir / filename, content, dry_run=dry_run)


def generate_code_artifact(
    path: Path,
    template: str,
    context: dict,
    dry_run: bool = False,
) -> dict:
    """Render a code artifact from a template string + context.

    Uses Python str.format() for simplicity — no external deps.  All
    placeholders are {key}; missing keys raise KeyError.
    """
    try:
        rendered = template.format(**context)
    except KeyError as exc:
        raise KeyError(f"missing template key: {exc}") from exc
    return generate_file(path, rendered, dry_run=dry_run)


# ---------------------------------------------------------------------------
# EXPLAIN pre-flight
# ---------------------------------------------------------------------------

EXPLAIN_DANGEROUS_PATTERNS = [
    re.compile(r"Seq Scan", re.IGNORECASE),
]

def explain_preflight(
    conn,
    sql: str,
    params: tuple | None = None,
    warn_on_seq_scan: bool = True,
) -> dict:
    """Run EXPLAIN on a SQL statement and return the plan.

    Returns {"ok": bool, "plan": str, "warnings": [str]}.  Does not execute
    the statement itself.  Caller decides whether warnings should block.
    The connection is expected to be a psycopg (sync) connection; falls back
    gracefully when no DB is available.
    """
    cleaned = sql.strip().rstrip(";")
    if not cleaned:
        return {"ok": True, "plan": "", "warnings": []}
    # EXPLAIN only the first statement; skip DDL that EXPLAIN can't handle well
    # We still attempt it — failure is reported as a warning, not a hard error,
    # so offline/dry-run usage doesn't crash.
    explain_sql = f"EXPLAIN {cleaned}"
    plan_text = ""
    warnings: List[str] = []
    try:
        with conn.cursor() as cur:
            if params is not None:
                cur.execute(explain_sql, params)
            else:
                cur.execute(explain_sql)
            rows = cur.fetchall()
            plan_text = "\n".join(r[0] if isinstance(r, (list, tuple)) else str(r) for r in rows)
    except Exception as exc:
        warnings.append(f"EXPLAIN failed: {exc}")
        return {"ok": False, "plan": plan_text, "warnings": warnings}

    if warn_on_seq_scan:
        for pat in EXPLAIN_DANGEROUS_PATTERNS:
            if pat.search(plan_text):
                # Heuristic: Seq Scan on a table > 0 rows deserves a warning.
                # We don't fail — we warn so the caller can decide.
                warnings.append(f"EXPLAIN warning: {pat.pattern!r} detected — consider adding an index")
                break
    return {"ok": True, "plan": plan_text, "warnings": warnings}


def explain_preflight_for_migration(
    conn,
    migration_sql: str,
) -> List[dict]:
    """Split a migration file into statements and EXPLAIN each SELECT/INSERT/UPDATE/DELETE.

    DDL statements are skipped for EXPLAIN but reported as {"skipped": True}.
    Returns a list of per-statement results.
    """
    # naive split on ; — good enough for pre-flight; not a SQL parser
    statements = [s.strip() for s in migration_sql.split(";") if s.strip()]
    results: List[dict] = []
    for stmt in statements:
        upper = stmt.lstrip().upper()
        if upper.startswith(("SELECT", "INSERT", "UPDATE", "DELETE", "WITH")):
            res = explain_preflight(conn, stmt + ";")
            res["statement"] = stmt[:120]
            results.append(res)
        else:
            results.append({"ok": True, "skipped": True, "statement": stmt[:120], "plan": "", "warnings": []})
    return results


# ---------------------------------------------------------------------------
# Audit helpers (V3 tables)
# ---------------------------------------------------------------------------

def audit_decision(
    conn,
    decision: str,
    rationale: str = "",
    context: dict | None = None,
    agent_identity: str = "architect",
    session_id: str | None = None,
    dry_run: bool = False,
) -> dict:
    """Write a row to agent_decision_audit (V3).  No-op in dry-run."""
    payload = {
        "decision": decision,
        "rationale": rationale,
        "context": context or {},
        "agent_identity": agent_identity,
        "session_id": session_id,
    }
    if dry_run:
        return {"written": False, "dry_run": True, **payload}
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO agent_decision_audit (agent_identity, session_id, decision, rationale, context)
                VALUES (%s, %s, %s, %s, %s::jsonb)
                """,
                (agent_identity, session_id, decision, rationale, json.dumps(context or {})),
            )
        if hasattr(conn, "commit"):
            conn.commit()
        return {"written": True, "dry_run": False, **payload}
    except Exception as exc:
        return {"written": False, "error": str(exc), "dry_run": False, **payload}


def audit_schema_change(
    conn,
    version: str,
    filename: str,
    checksum: str | None,
    description: str = "",
    execution_time_ms: int = 0,
    dry_run: bool = False,
) -> dict:
    """Write a row to schema_change_audit (V3).  No-op in dry-run."""
    payload = {
        "version": version,
        "filename": filename,
        "checksum": checksum,
        "description": description,
        "execution_time_ms": execution_time_ms,
    }
    if dry_run:
        return {"written": False, "dry_run": True, **payload}
    try:
        with conn.cursor() as cur:
            cur.execute(
                """
                INSERT INTO schema_change_audit (version, filename, checksum, description, execution_time_ms)
                VALUES (%s, %s, %s, %s, %s)
                """,
                (version, filename, checksum, description, execution_time_ms),
            )
        if hasattr(conn, "commit"):
            conn.commit()
        return {"written": True, "dry_run": False, **payload}
    except Exception as exc:
        return {"written": False, "error": str(exc), "dry_run": False, **payload}


# ---------------------------------------------------------------------------
# Pin-memory weighted boost (Librarian C10 tuning)
# ---------------------------------------------------------------------------

def compute_pin_boost(
    base_score: float,
    pin_weight: float = 0.0,
    ttl_seconds: float = 3600.0,
    age_seconds: float = 0.0,
) -> float:
    """Compute boosted score for a pinned memory.

    Formula:
        boosted = base_score * (1 + pin_weight * decay)
        decay   = exp(-age / ttl)   if ttl > 0 else 1.0

    pin_weight: multiplicative boost (e.g. 0.5 = +50% at age 0)
    ttl_seconds: time constant for decay; 0 or negative means no decay.
    age_seconds: elapsed since pin (now - pinned_at); negative clamped to 0.
    """
    if pin_weight <= 0:
        return float(base_score)
    age_seconds = max(0.0, float(age_seconds))
    pin_weight = float(pin_weight)
    ttl_seconds = float(ttl_seconds)
    if ttl_seconds <= 0:
        decay = 1.0
    else:
        decay = math.exp(-age_seconds / ttl_seconds)
    return float(base_score) * (1.0 + pin_weight * decay)


def apply_pin_boost(
    candidates: List[dict],
    pin_weight: float = 1.0,
    ttl_seconds: float = 86400.0,
    now: float | None = None,
) -> List[dict]:
    """Apply pin boost to a list of candidate dicts.

    Each candidate may contain: {score, pinned, pinned_at, pin_weight, ttl}
    pinned_at is an epoch seconds or ISO8601 string; if absent age=0.
    Returns a new list sorted by boosted_score descending; each item gains
    `boosted_score` and `pin_decay` keys.  Non-pinned items keep their score.
    """
    if now is None:
        now = time.time()
    out: List[dict] = []
    for c in candidates:
        base = float(c.get("score", 0.0))
        if not c.get("pinned"):
            boosted = base
            decay = 0.0
        else:
            pw = float(c.get("pin_weight", pin_weight))
            ttl = float(c.get("ttl", ttl_seconds))
            pinned_at = c.get("pinned_at")
            age = 0.0
            if pinned_at is not None:
                try:
                    if isinstance(pinned_at, (int, float)):
                        age = float(now) - float(pinned_at)
                    elif isinstance(pinned_at, str):
                        # try ISO8601
                        dt = datetime.datetime.fromisoformat(pinned_at.replace("Z", "+00:00"))
                        age = float(now) - dt.timestamp()
                    else:
                        age = 0.0
                except Exception:
                    age = 0.0
            boosted = compute_pin_boost(base, pw, ttl, age)
            # recompute decay for reporting
            if ttl <= 0:
                decay = 1.0
            else:
                decay = math.exp(-max(0.0, age) / ttl)
        item = dict(c)
        item["boosted_score"] = boosted
        item["pin_decay"] = decay
        out.append(item)
    out.sort(key=lambda x: x["boosted_score"], reverse=True)
    return out


# ---------------------------------------------------------------------------
# hits.jsonl logger
# ---------------------------------------------------------------------------

DEFAULT_HITS_PATH = Path("data/hits.jsonl")

def log_hit(
    entry: dict,
    hits_file: Path | str = DEFAULT_HITS_PATH,
    pin_weight: float | None = None,
    ttl: float | None = None,
    dry_run: bool = False,
) -> dict:
    """Append a single hit record to hits.jsonl (JSON Lines).

    entry: arbitrary dict; will be enriched with _ts, pin_weight, ttl if supplied.
    Returns the enriched record.  In dry-run nothing is written.
    """
    p = Path(hits_file)
    record = dict(entry)
    record.setdefault("_ts", datetime.datetime.now(datetime.timezone.utc).isoformat())
    if pin_weight is not None:
        record["pin_weight"] = float(pin_weight)
    if ttl is not None:
        record["ttl"] = float(ttl)
    # compute boosted_score if score present
    if "score" in record and "pin_weight" in record:
        try:
            age = float(record.get("age_seconds", 0.0))
            ttl_v = float(record.get("ttl", 3600.0))
            pw = float(record["pin_weight"])
            record["boosted_score"] = compute_pin_boost(float(record["score"]), pw, ttl_v, age)
        except Exception:
            pass
    if dry_run:
        record["_dry_run"] = True
        return record
    p.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(record, ensure_ascii=False)
    with p.open("a", encoding="utf-8") as fh:
        fh.write(line + "\n")
    return record


def read_hits(
    hits_file: Path | str = DEFAULT_HITS_PATH,
    limit: int = 100,
) -> List[dict]:
    """Read last `limit` hits from hits.jsonl."""
    p = Path(hits_file)
    if not p.exists():
        return []
    lines = p.read_text(encoding="utf-8").strip().splitlines()
    out: List[dict] = []
    for line in lines[-limit:]:
        line = line.strip()
        if not line:
            continue
        try:
            out.append(json.loads(line))
        except json.JSONDecodeError:
            continue
    return out


# ---------------------------------------------------------------------------
# Webhook notification
# ---------------------------------------------------------------------------

def notify_webhook(
    payload: dict,
    url: str | None = None,
    dry_run: bool = False,
    timeout: float = 5.0,
) -> dict:
    """POST payload as JSON to the webhook URL.

    URL resolved from arg or HERMES_WEBHOOK_URL env var.  Returns
    {"notified": bool, "url": str|None, "dry_run": bool, ...}.
    Failures are swallowed (agent must not crash on webhook outage).
    """
    webhook_url = url or os.environ.get("HERMES_WEBHOOK_URL", "").strip()
    if not webhook_url:
        return {"notified": False, "url": None, "reason": "no webhook URL configured"}
    if dry_run:
        return {"notified": False, "url": webhook_url, "dry_run": True, "payload": payload}
    try:
        import urllib.request

        data = json.dumps(payload, ensure_ascii=False).encode("utf-8")
        req = urllib.request.Request(
            webhook_url,
            data=data,
            headers={"Content-Type": "application/json", "User-Agent": "hermes-architect/2.0"},
            method="POST",
        )
        with urllib.request.urlopen(req, timeout=timeout) as resp:
            body = resp.read().decode("utf-8", errors="replace")[:2000]
            return {"notified": True, "url": webhook_url, "status": resp.status, "body": body}
    except Exception as exc:
        return {"notified": False, "url": webhook_url, "error": str(exc)}


# ---------------------------------------------------------------------------
# gh PR creation
# ---------------------------------------------------------------------------

def create_pr(
    branch: str,
    title: str,
    body: str,
    base: str = "main",
    dry_run: bool = False,
) -> dict:
    """Create a GitHub PR via `gh` CLI.

    Assumes the branch already exists remotely (push first).  Returns
    {"created": bool, "dry_run": bool, "pr_url": str|None, ...}.
    """
    if dry_run:
        return {"created": False, "dry_run": True, "branch": branch, "title": title, "base": base}
    # verify gh exists
    try:
        subprocess.run(["gh", "--version"], capture_output=True, check=True)
    except (FileNotFoundError, subprocess.CalledProcessError):
        return {"created": False, "error": "gh CLI not found; install gh or set HERMES_GITHUB_TOKEN"}
    cmd = ["gh", "pr", "create", "--base", base, "--head", branch, "--title", title, "--body", body]
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=30)
        if result.returncode == 0:
            url = result.stdout.strip().splitlines()[-1] if result.stdout.strip() else None
            return {"created": True, "dry_run": False, "pr_url": url, "stdout": result.stdout}
        return {"created": False, "error": result.stderr.strip() or result.stdout.strip(), "returncode": result.returncode}
    except Exception as exc:
        return {"created": False, "error": str(exc)}


def git_push_branch(branch: str, dry_run: bool = False) -> dict:
    """Push the current branch to origin.  No-op in dry-run."""
    if dry_run:
        return {"pushed": False, "dry_run": True, "branch": branch}
    try:
        result = subprocess.run(["git", "push", "-u", "origin", branch], capture_output=True, text=True, timeout=30)
        if result.returncode == 0:
            return {"pushed": True, "stdout": result.stdout}
        return {"pushed": False, "error": result.stderr.strip(), "returncode": result.returncode}
    except Exception as exc:
        return {"pushed": False, "error": str(exc)}


# ---------------------------------------------------------------------------
# High-level run helper (used by CLI + tests)
# ---------------------------------------------------------------------------

def run_architect(
    dry_run: bool = False,
    branch: str | None = None,
    title: str | None = None,
    body: str | None = None,
    base: str = "main",
    force: bool = False,
    dsn: str | None = None,
    webhook_payload: dict | None = None,
) -> int:
    """High-level orchestration (dry-run aware, kill-switch gated).

    Returns an exit code (0 = success/skip, 1 = error).
    """
    if not require_enabled(force=force):
        print("architect: HERMES_AGENT_ENABLED != true — kill switch active, exiting (no-op).", file=sys.stderr)
        return 0

    if dry_run:
        print("architect: DRY-RUN — no files, DB writes, pushes, or webhooks will execute.")
        if branch:
            print(f"  would push branch: {branch}")
        if title:
            print(f"  would create PR: {title!r} ({base} <- {branch})")
        if webhook_payload or os.environ.get("HERMES_WEBHOOK_URL"):
            print("  would notify webhook: HERMES_WEBHOOK_URL")
        print("  would log hit to data/hits.jsonl (dry-run: not written)")
        return 0

    # Real run: if branch/title provided, do git push + PR + webhook
    if branch and title:
        push_res = git_push_branch(branch, dry_run=False)
        if not push_res.get("pushed"):
            print(f"architect: git push failed: {push_res.get('error')}", file=sys.stderr)
            return 1
        pr_res = create_pr(branch, title, body or "", base=base, dry_run=False)
        if not pr_res.get("created"):
            print(f"architect: gh pr create failed: {pr_res.get('error')}", file=sys.stderr)
            return 1
        print(f"architect: PR created: {pr_res.get('pr_url')}")
        if webhook_payload is None:
            webhook_payload = {"event": "architect.pr_created", "branch": branch, "title": title, "pr_url": pr_res.get("pr_url")}
        notify_webhook(webhook_payload)
    elif webhook_payload:
        notify_webhook(webhook_payload)
    return 0


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description="Architect v2 — autonomous agent hooks (kill switch gated)")
    ap.add_argument("--dry-run", action="store_true", help="Print actions without side-effects")
    ap.add_argument("--force", action="store_true", help="Bypass HERMES_AGENT_ENABLED gate (local testing)")
    ap.add_argument("--branch", default=None, help="Branch to push / create PR from")
    ap.add_argument("--title", default=None, help="PR title")
    ap.add_argument("--body", default="", help="PR body")
    ap.add_argument("--base", default="main", help="PR base branch (default: main)")
    ap.add_argument("--dsn", default=None, help="Postgres DSN (for EXPLAIN pre-flight)")
    ap.add_argument("--check-enabled", action="store_true", help="Print kill-switch status and exit")
    ap.add_argument("--migrations-dir", default=None, help="Path to sql/migrations (for file generation)")
    ap.add_argument("--generate-migration", nargs=3, metavar=("VERSION", "DESCRIPTION", "SQL_FILE"),
                    help="Generate a migration file: VERSION DESCRIPTION SQL_FILE (reads SQL_FILE)")
    ap.add_argument("--hits-file", default=str(DEFAULT_HITS_PATH), help="hits.jsonl path")
    ap.add_argument("--pin-weight", type=float, default=None, help="Pin boost weight (for hits logger)")
    ap.add_argument("--ttl", type=float, default=None, help="Pin TTL seconds (for hits logger)")
    args = ap.parse_args(argv)

    if args.check_enabled:
        enabled = is_agent_enabled()
        print(f"HERMES_AGENT_ENABLED={'true' if enabled else 'false'}")
        return 0

    if not require_enabled(force=args.force):
        print("architect: HERMES_AGENT_ENABLED != true — kill switch active, exiting (no-op).", file=sys.stderr)
        return 0

    if args.generate_migration:
        version, description, sql_file = args.generate_migration
        migrations_dir = Path(args.migrations_dir) if args.migrations_dir else Path("sql/migrations")
        sql_body = Path(sql_file).read_text(encoding="utf-8") if Path(sql_file).exists() else sql_file
        # optional EXPLAIN pre-flight if DSN provided
        if args.dsn:
            try:
                import psycopg
                with psycopg.connect(args.dsn, autocommit=True) as conn:
                    results = explain_preflight_for_migration(conn, sql_body)
                    for r in results:
                        if r.get("warnings"):
                            print(f"EXPLAIN warning for {r.get('statement','')!r}: {r['warnings']}", file=sys.stderr)
            except Exception as exc:
                print(f"EXPLAIN pre-flight skipped: {exc}", file=sys.stderr)
        res = generate_migration_file(migrations_dir, version, description, sql_body, dry_run=args.dry_run)
        print(f"{'would generate' if args.dry_run else 'generated'}: {res['path']}  sha256:{res['checksum'][:12]}")
        return 0

    # Generic high-level run (push/PR/webhook)
    return run_architect(
        dry_run=args.dry_run,
        branch=args.branch,
        title=args.title,
        body=args.body,
        base=args.base,
        force=args.force,
        dsn=args.dsn,
    )


if __name__ == "__main__":
    sys.exit(main())
